### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by fbarth75** [bain3/pronotepy#120]
Got an error with my ent "monbureaunumerique" , i'm  apparently logged on 2 differents ent...
```
DEBUG:pronotepy.ent.cas_edu:[ENT Mon bureau numérique] Logging in with 4A4A596AA0EF
DEBUG:pronotepy.ent.cas_edu:[ENT Occitanie] Logging in with 4A4A596AA0EF
DEBUG:pronotepy.pronoteAPI:Requesing html: https://0100008e.index-education.net/pronote/eleve.html
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pronotepy/clients.py", line 241, in post
    return self.communication.post(function_name, post_data)
  File "/usr/local/lib/python3.9/dist-packages/pronotepy/pronoteAPI.py", line 138, in post
    raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: [ERROR 25] Exceeded max authorization requests. Please wait before retrying...
```

**Comment by fbarth75** [comment]
Same error with the latest version ...

```
DEBUG:pronotepy.ent.cas_edu:[ENT Mon bureau numérique] Logging in with 5B907A61BA8E
DEBUG:pronotepy.ent.cas_edu:[ENT Occitanie] Logging in with 5B907A61BA8E
DEBUG:pronotepy.pronoteAPI:Requesing html: https://0100008e.index-education.net/pronote/parent.html
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pronotepy/clients.py", line 576, in post
    return self.communication.post(function_name, post_data)
  File "/usr/local/lib/python3.9/dist-packages/pronotepy/pronoteAPI.py", line 138, in post
    raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: Unknown error from pronote: 7 | Votre adresse IP est provisoirement suspendue !
```

**Comment by Bapt5** [comment]
This error just mean that your IP was blocked. This is not a problem with pronotepy

**Comment by Bapt5** [comment]
@bain3 I think we can close this because it's not a pronotepy issue
