### ISSUE TITLE
IP filter on enc_hauts_de_seine

### ISSUE THREAD

**Issue by lesensei** [bain3/pronotepy#165]
Hello,
I'm trying to use pronotepy to fetch data from the Hauts-de-Seine instance as a parent.
Here's my code at the moment:
```
import pronotepy
from pronotepy.ent import enc_hauts_de_seine

client = pronotepy.ParentClient("https://0920xxxj.index-education.net/pronote/parent.html", username="prenom.nom@enc.hauts-de-seine.fr", password="motdepasse", ent=enc_hauts_de_seine)

if client.logged_in:
    print(client.children[0].name)
else:
    print("no login")
```
This code works quite well in a docker container... on the condition that I log in to Pronote from the same public IP address before running it. Otherwise, I get a `PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.` error.

I'm opening this issue, but I'm not sure if this should indeed be considered an issue with pronotepy. I guess if you reject it as `wontfix` I'll end up trying to script something in order to emulate a connection from the browser before calling pronotepy...

Thanks anyways.

**Comment by lesensei** [comment]
In case this might be in any way useful, here is the debug log from a session where I didn't log in first from my browser:
```
# python test.py
INFO:pronotepy.pronoteAPI:INIT
DEBUG:pronotepy.ent.generic_func:[ENT https://enc.hauts-de-seine.fr/] Logging in with prenom.nom@enc.hauts-de-seine.fr
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): enc.hauts-de-seine.fr:443
DEBUG:urllib3.connectionpool:https://enc.hauts-de-seine.fr:443 "GET / HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Resetting dropped connection: enc.hauts-de-seine.fr
DEBUG:urllib3.connectionpool:https://enc.hauts-de-seine.fr:443 "GET /my.policy HTTP/1.1" 200 32523
DEBUG:urllib3.connectionpool:Resetting dropped connection: enc.hauts-de-seine.fr
DEBUG:urllib3.connectionpool:https://enc.hauts-de-seine.fr:443 "POST /my.policy HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Resetting dropped connection: enc.hauts-de-seine.fr
DEBUG:urllib3.connectionpool:https://enc.hauts-de-seine.fr:443 "GET / HTTP/1.1" 301 None
DEBUG:urllib3.connectionpool:https://enc.hauts-de-seine.fr:443 "GET /fr/ HTTP/1.1" 200 None
DEBUG:pronotepy.pronoteAPI:Requesing html: https://0920xxxj.index-education.net/pronote/parent.html
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 0920xxxj.index-education.net:443
DEBUG:urllib3.connectionpool:https://0920xxxj.index-education.net:443 "GET /pronote/parent.html HTTP/1.1" 302 165
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): enc.hauts-de-seine.fr:443
DEBUG:urllib3.connectionpool:https://enc.hauts-de-seine.fr:443 "GET /cas/login?service=https:%2F%2F0920xxxJ.index-education.net%2Fpronote%2Fparent.html HTTP/1.1" 200 None
DEBUG:charset_normalizer:Encoding detection: utf_8 is most likely the one.
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    client = pronotepy.ParentClient("https://0920xxxj.index-education.net/pronote/parent.html", username="prenom.nom@enc.hauts-de-seine.fr", password="motdepasse", ent=enc_hauts_de_seine)
  File "/usr/local/lib/python3.10/site-packages/pronotepy/clients.py", line 701, in __init__
    super().__init__(pronote_url, username, password, ent, qr_code)
  File "/usr/local/lib/python3.10/site-packages/pronotepy/clients.py", line 382, in __init__
    super().__init__(pronote_url, username, password, ent, qr_code)
  File "/usr/local/lib/python3.10/site-packages/pronotepy/clients.py", line 81, in __init__
    self.attributes, self.func_options = self.communication.initialise()
  File "/usr/local/lib/python3.10/site-packages/pronotepy/pronoteAPI.py", line 77, in initialise
    self.attributes = self._parse_html(get_response.content)
  File "/usr/local/lib/python3.10/site-packages/pronotepy/pronoteAPI.py", line 274, in _parse_html
    raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.
#
```
And here's a successful session, after logging in through my browser and relaunching the same script:
```
# python test.py
INFO:pronotepy.pronoteAPI:INIT
DEBUG:pronotepy.ent.generic_func:[ENT https://enc.hauts-de-seine.fr/] Logging in with alain.perry@enc.hauts-de-seine.fr
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): enc.hauts-de-seine.fr:443
DEBUG:urllib3.connectionpool:https://enc.hauts-de-seine.fr:443 "GET / HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Resetting dropped connection: enc.hauts-de-seine.fr
DEBUG:urllib3.connectionpool:https://enc.hauts-de-seine.fr:443 "GET /my.policy HTTP/1.1" 200 32523
DEBUG:urllib3.connectionpool:Resetting dropped connection: enc.hauts-de-seine.fr
DEBUG:urllib3.connectionpool:https://enc.hauts-de-seine.fr:443 "POST /my.policy HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Resetting dropped connection: enc.hauts-de-seine.fr
DEBUG:urllib3.connectionpool:https://enc.hauts-de-seine.fr:443 "GET / HTTP/1.1" 301 None
DEBUG:urllib3.connectionpool:https://enc.hauts-de-seine.fr:443 "GET /fr/ HTTP/1.1" 200 None
DEBUG:pronotepy.pronoteAPI:Requesing html: https://0920xxxj.index-education.net/pronote/parent.html
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 0920xxxj.index-education.net:443
DEBUG:urllib3.connectionpool:https://0920xxxj.index-education.net:443 "GET /pronote/parent.html HTTP/1.1" 302 165
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): enc.hauts-de-seine.fr:443
DEBUG:urllib3.connectionpool:https://enc.hauts-de-seine.fr:443 "GET /cas/login?service=https:%2F%2F0920xxxJ.index-education.net%2Fpronote%2Fparent.html HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://0920xxxj.index-education.net:443 "GET /pronote/parent.html?ticket=ST-xxxxxxxx-xxxxxxxxxxxxxxx-OZE-HDS HTTP/1.1" 302 165
DEBUG:urllib3.connectionpool:https://0920xxxj.index-education.net:443 "GET /pronote/parent.html?identifiant=xxxxxxxxxxxxxxxx HTTP/1.1" 200 2065
DEBUG:charset_normalizer:Encoding detection: utf_8 is most likely the one.
DEBUG:urllib3.connectionpool:https://0920xxxj.index-education.net:443 "POST /pronote/appelfonction/2/722130/3fa959b13967e0ef176069e0xxxxxxxx HTTP/1.1" 200 23337
DEBUG:pronotepy.pronoteAPI:[_Communication.post] decryption change
DEBUG:urllib3.connectionpool:https://0920xxxj.index-education.net:443 "POST /pronote/appelfonction/2/722130/ce5dc3040a5ad34df7d86dbdxxxxxxxx HTTP/1.1" 200 204
DEBUG:pronotepy.pronoteAPI:indentification
DEBUG:pronotepy.pronoteAPI:{'nom': 'Identification', 'session': xxxxxx, 'numeroOrdre': 'xxxxxx', 'donneesSec': {'donnees': {'challenge': 'xxxxxx'}, 'nom': 'Identification'}}
DEBUG:urllib3.connectionpool:https://0920xxxj.index-education.net:443 "POST /pronote/appelfonction/2/722130/69b07a91984bbab83d5b139exxxxxxxx HTTP/1.1" 200 306
INFO:pronotepy.pronoteAPI:successfully logged in as xxxxxxxxxxxx
DEBUG:urllib3.connectionpool:https://0920xxxj.index-education.net:443 "POST /pronote/appelfonction/2/722130/79178e597cd886465dfceda0xxxxxxxx HTTP/1.1" 200 21414
INFO:pronotepy.pronoteAPI:got onglets data.
NOM Prenom
#
```

**Comment by Bapt5** [comment]
To simplify you say that it's work when you start a connexion before on the same IP with a browser and it's doesn't work otherwise?

**Comment by lesensei** [comment]
Yes, precisely. Sorry if that wasn't obvious.

**Comment by lesensei** [comment]
Looking at a session with Dev Tools in Firefox, it looks like what is missing is a GET on `https://enc.hauts-de-seine.fr/cas/proxySSO/yyyyyy?uai=0920xxxJ&projet=OZE_HDS&fonction=TUT` where `yyyyyy` is a hex string that can be obtained as a json attribute through a prior GET on `https://api-enc.hauts-de-seine.fr/v1/config/Pronote?ctx_profil=RESPONSABLE_ELEVE&ctx_etab=0920xxxJ` (in the case of `ParentClient`, not sure for `Client`, but I could check).
Once that `proxySSO` call is made, I'm pretty sure the rest will work without a glitch.
I'm not yet sure I'll be able to understand enough of the pronotepy code to make a working patch, but I'll try my luck as soon as I can allocate time for that.

**Comment by Bapt5** [comment]
I have not a lot of time for the moment if you can't make a fix I'll do it later.
