### ISSUE TITLE
Error: Fail to connect with EduConnect : probably wrong login information

### ISSUE THREAD

**Issue by Didoub74-Off** [bain3/pronotepy#176]
Hello again,
I've got this error: 
`Traceback (most recent call last):
  File "main.py", line 9, in <module>
    client = pronotepy.Client(
  File "/home/runner/Pronote-Note-Mailer/venv/lib/python3.8/site-packages/pronotepy/clients.py", line 347, in __init__
    super().__init__(pronote_url, username, password, ent, qr_code)
  File "/home/runner/Pronote-Note-Mailer/venv/lib/python3.8/site-packages/pronotepy/clients.py", line 64, in __init__
    cookies = ent(username, password, pronote_url=pronote_url)
  File "/home/runner/Pronote-Note-Mailer/venv/lib/python3.8/site-packages/pronotepy/ent/generic_func.py", line 130, in _cas_edu
    _educonnect(session, username, password, response.url)
  File "/home/runner/Pronote-Note-Mailer/venv/lib/python3.8/site-packages/pronotepy/ent/generic_func.py", line 55, in _educonnect
    raise ENTLoginError(
pronotepy.exceptions.ENTLoginError: Fail to connect with EduConnect : probably wrong login information`

And this code: 
```
import pronotepy
from time import sleep
from pronotepy.ent import ent_auvergnerhonealpe
from sendMail import send_mail
from replit import db
import datetime

while True:  # infinite loop
    client = pronotepy.Client(
        'https://rne.index-education.net/pronote/eleve.html',
        username='username',
        password='Password',
        ent=ent_auvergnerhonealpe)
    # check if sucessfully logged in
    if not client.logged_in:
        print("Client is not logged in")
        exit()
```

I'm sure that my ID are correct, 
Can you help me
Sincereley Didoub74

**Comment by Bapt5** [comment]
@Didoub74-Off Do you use Educonnect when you are accessing to Pronote or are you using an other authentification method ?
