### ISSUE TITLE
Error when connecting with CAS: ent_grenoble

### ISSUE THREAD

**Issue by Didoub74-Off** [bain3/pronotepy#178]
Hello,
I'm getting this error:
`Traceback (most recent call last):
  File "main.py", line 9, in <module>
    client = pronotepy.Client(
  File "/home/runner/Pronote-Note-Mailer/venv/lib/python3.8/site-packages/pronotepy/clients.py", line 347, in __init__
    super().__init__(pronote_url, username, password, ent, qr_code)
  File "/home/runner/Pronote-Note-Mailer/venv/lib/python3.8/site-packages/pronotepy/clients.py", line 64, in __init__
    cookies = ent(username, password, pronote_url=pronote_url)
  File "/home/runner/Pronote-Note-Mailer/venv/lib/python3.8/site-packages/pronotepy/ent/generic_func.py", line 172, in _cas
    for input_ in form.findAll("input"):
AttributeError: 'NoneType' object has no attribute 'findAll'`

with this code:
```
client = pronotepy.Client(
        'https://0740006e.index-education.net/pronote/eleve.html',
        username='first.last',
        password='Password',
        ent=ac_grenoble)
    # check if sucessfully logged in
    if not client.logged_in:
        print("Client is not logged in")
        exit()
    else:
        print("Hey")
        exit()
```

**Comment by Bapt5** [comment]
Hi @Didoub74-Off I don't have this error. Can you try again ?
