### ISSUE TITLE
Punishment: seems not to work for student access

### ISSUE THREAD

**Issue by vingerha** [bain3/pronotepy#184]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Funded-%2300A156.svg" />](https://issuehunt.io/r/bain3/pronotepy/issues/184)

I thought to have reported this earlier but cannot find a trace so with the risk of repeating myself...
I tried to use the setup as proposed / tested but receive error

```
if client.logged_in: # check if client successfully logged in
    periods = client.periods
    jsondata2 = {}
    jsondata2['punishments'] = []
    for period in periods:
        for punnishment in period.punishments:
            jsondata2['punishments'].append({
                'pid': period.id,
                'periodName': period.name,
                'periodStart': period.start.strftime("%Y/%m/%d"),
                'periodEnd': period.end.strftime("%Y/%m/%d"),
                'given': punnishment.given,
            })
```

```
Traceback (most recent call last):
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 195, in __call__
    json_value = json_value[p]
KeyError: 'estAvecARParent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/3692670A6ACD9016/docker/homeassistant1/python_scripts/pronote_old_attempts/test.py", line 33, in <module>
    for punnishment in period.punishments:
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 402, in punishments
    return [Punishment(self._client, a) for a in absences if a["G"] == 41]
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 402, in <listcomp>
    return [Punishment(self._client, a) for a in absences if a["G"] == 41]
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 1854, in __init__
    self.requires_parent: str = self._resolver(
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 205, in __call__
    raise ParsingError("Could not follow path", self.json_dict, path)
pronotepy.exceptions.ParsingError: Could not follow path
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars.githubusercontent.com/u/44190435?v=4' alt='vingerha' width=24 height=24> vingerha](https://issuehunt.io/u/vingerha) ($2.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/bain3/pronotepy/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by bain3** [comment]
Hmm the `test_punishments` unit test is connecting as a student, and is passing. It might be that your PRONOTE differs. It's not unusual that the demo version differs a bit. I'll try to make this `Optional`.

**Comment by vingerha** [comment]
Thanks for the quick response, could you maybe send me the json path/structure to this data so I can test it out as well on what I see or not, just to be clear...my son has (few!) punishments so data is there

**Comment by bain3** [comment]
Hi, you can find the data in a `PagePresence` request when you go to Vie Scolaire -> Récapitulatif. The demo website has a single punishment:
<details>
<summary>Expand for JSON</summary>

```json
{
    "N": "121B90804929422",
    "G": 41,
    "dateDemande":
    {
        "_T": 7,
        "V": "01/09/2022"
    },
    "placeDemande": 62,
    "estUneExclusion": false,
    "horsCours": false,
    "travailAFaire": "Exercices 1 à 18 p283-284",
    "estLieAUnIncident": false,
    "documentsTAF":
    {
        "_T": 24,
        "V": []
    },
    "documentsCirconstances":
    {
        "_T": 24,
        "V": []
    },
    "nature":
    {
        "_T": 24,
        "V":
        {
            "L": "Retenue",
            "N": "1056A08BA40AB97",
            "G": 1,
            "estProgrammable": true,
            "estAvecARParent": true
        }
    },
    "parentAAccuseDeReception": false,
    "matiere":
    {
        "_T": 24,
        "V":
        {
            "N": "0"
        }
    },
    "duree": 60,
    "circonstances": "Insultes suite à une réprimande",
    "listeMotifs":
    {
        "_T": 24,
        "V":
        [
            {
                "L": "Violence verbale",
                "N": "98A3A559C08F50"
            }
        ]
    },
    "demandeur":
    {
        "_T": 24,
        "V":
        {
            "L": "M. PROFESSEUR M.",
            "N": "11673BE843CF709",
            "G": 3
        }
    },
    "estProgrammable": true,
    "programmation":
    {
        "_T": 24,
        "V":
        [
            {
                "N": "1174B504F77C26D",
                "G": 52,
                "date":
                {
                    "_T": 7,
                    "V": "07/09/2022"
                },
                "placeExecution": 11,
                "duree": 60
            }
        ]
    },
    "page":
    {
        "Onglet": 19,
        "Membre": "A408C09E675F",
        "Absence": 41,
        "message": ""
    }
}
```

</details>

**Comment by vingerha** [comment]
Did not need to seek, your fix worked (using master.zip)...thanks for the quick turnaround

**Comment by bain3** [comment]
Sorry, didn't have an actuall PR to link this to. You can give rewards to previous PRs, good to know!
