### ISSUE TITLE
Je n'arrive pas à me connecter 

### ISSUE THREAD

**Issue by Raphiiti** [bain3/pronotepy#220]
Bonjour / Bonsoir,
J'essaie de me connecter avec le script mais la console me retourne des erreurs. Comment faire ?

Voici mon code:

```
import pronotepy
from pronotepy.ent import ac_rennes
# importing ent specific function, you do not need to import anything if you dont use an ent

client = pronotepy.Client('https://www.toutatice.fr/portail',
                          username='Rick',
                          password='Astley',
                          ent=ac_rennes)  # ent specific
if not client.logged_in:
    exit(1)  # the client has failed to log in

if client.logged_in:
    print("Ca marche !")
else:
    print("Ca ne marche pas ")
```
Et voici ce que me retourne la console :

```
Traceback (most recent call last):
  File "c:\Users\Desktop\RaphiBot\pronote.py", line 5, in <module>
    client = pronotepy.Client('https://www.toutatice.fr/portail',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\RaphiBot\env\Lib\site-packages\pronotepy\clients.py", line 352, in __init__
    super().__init__(pronote_url, username, password, ent, qr_code)
  File "C:\Users\Desktop\RaphiBot\env\Lib\site-packages\pronotepy\clients.py", line 75, in __init__
    self.attributes, self.func_options = self.communication.initialise()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\RaphiBot\env\Lib\site-packages\pronotepy\pronoteAPI.py", line 76, in initialise
    self.attributes = self._parse_html(get_response.content)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\RaphiBot\env\Lib\site-packages\pronotepy\pronoteAPI.py", line 264, in _parse_html
    raise PronoteAPIError("Your IP address is suspended.")
pronotepy.exceptions.PronoteAPIError: Your IP address is suspended.
(env)
```

Bonne journée / soirée.

Raphiiti

**Comment by Bapt5** [comment]
Bonjour Comme l'indique l'erreur ton IP est suspendu par le site Pronote. Le problème ne vient donc pas de pronotepy.
