### ISSUE TITLE
Punishments inconsistent working and not with current_period

### ISSUE THREAD

**Issue by vingerha** [bain3/pronotepy#225]
I added punishments a few months ago and this was working fine along
```
    periods = client.periods
    jsondata = {}
    jsondata['punishments'] = []
    for period in periods:       
    for punishment in client.current_period.punishments:
        jsondata['punishments'].append({
            'pid': period.id,
            'periodName': period.name,
            'periodStart': period.start.strftime("%Y/%m/%d"),
            'periodEnd': period.end.strftime("%Y/%m/%d"),
            'punid': punishment.id,
            'punishmentDate': punishment.given.strftime("%Y/%m/%d"),
            'punishmentDuringLesson': punishment.during_lesson,
            'punishmentCircumstances': punishment.circumstances,
            'punishmentReasons': punishment.reasons,
            'punishmentNature': punishment.nature,
            'punishmentDuration': str(punishment.duration)[:4],
            'punishmentHomework': punishment.homework,
            'punishmentExclusion': punishment.exclusion,
        })
    punishmentList = jsondata
    print(jsondata)   
```
In this process, the first period is "Trimestre 1", this goes fine for the punishments received
Then it goes into Trimestre2 (since Feb) and it crashes
I tried for Semestre 1 (works() and Semestre 2 (crash) as well 
```
Traceback (most recent call last):
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 206, in __call__
    json_value = json_value[p]
KeyError: 'placeExecution'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 221, in __call__
    json_value = converter(json_value)
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 1821, in <lambda>
    lambda x: [Punishment.ScheduledPunishment(client, i) for i in x],
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 1821, in <listcomp>
    lambda x: [Punishment.ScheduledPunishment(client, i) for i in x],
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 1758, in __init__
    place = self._resolver(int, "placeExecution")
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 216, in __call__
    raise ParsingError("Could not follow path", self.json_dict, path)
pronotepy.exceptions.ParsingError: Could not follow path

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/3692670A6ACD9016/docker/homeassistant1/python_scripts/pronote_old_attempts/test.py", line 38, in <module>
    for punishment in period.punishments:
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 523, in punishments
    return [Punishment(self._client, a) for a in absences if a["G"] == 41]
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 523, in <listcomp>
    return [Punishment(self._client, a) for a in absences if a["G"] == 41]
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 1820, in __init__
    self.schedule = self._resolver(
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 223, in __call__
    raise ParsingError(
pronotepy.exceptions.ParsingError: Error while converting value: Could not follow path
```
My assumption is that it crashes because of non-existing punishments assigned to Trimestre2
However, I do see one assigned in pronote-app for semsestre2
I tried to use client.current_period.punishments but this crashes too

My preference would be that it provides the data for 'current_period' at a minimum, it should at least not crash for others.

EDIT:
To make it more clear, I checked individual periods (as per client.periods)
- Trimestre 1, contains 4, shows fine
- Trimestre 2, contains 1, crash
- Trimestre 3, contains 0, shows 0 no crash
- Semestre 1, contains 4, shows fine
- Semestre 2, contains 1, crash
- Année continue, contains 5, crash
- Bac blanc, should not apply for my kid,: crash
- DNB Blanc, should not apply for my kid,: crash
- Hors période: crash
- Contrôle en cours de formation: crash

**Comment by bain3** [comment]
So is it crashing when there shouldn't be any punishments? This just looks like `placeExecution` could be null / not there. I'll fix that.

**Comment by bain3** [comment]
btw https://pronotepy.readthedocs.io/en/stable/quickstart.html#json-serialization

**Comment by vingerha** [comment]
> So is it crashing when there shouldn't be any punishments? This just looks like `placeExecution` could be null / not there. I'll fix that.
Not really, it does not crash for future Trimestre 3 which obviously has no punishments yet (I hope that stays that way :) )
But Semestre 2 has already 1 and so does Trimestre 2 ... they crash.
Could also be that the punishment record is making it crash?
Is there an alternative way to get to the object containing the single punishment in Sem/Tim 2? 
I forgot to tell , running this on v2.9.0
And, I can of course help testing any proposal you have.

**Comment by vingerha** [comment]
> btw https://pronotepy.readthedocs.io/en/stable/quickstart.html#json-serialization

That one returns:
```
Traceback (most recent call last):
  File "/mnt/3692670A6ACD9016/docker/homeassistant1/python_scripts/pronote_old_attempts/test.py", line 38, in <module>
    serialized = period.to_dict(include_properties=True, exclude={"punishments", })
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 282, in to_dict
    slot = getattr(self, slot_name)
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 420, in averages
    crs = response["donneesSec"]["donnees"]["listeServices"]["V"]
KeyError: 'listeServices'

**Comment by vingerha** [comment]
Got a 2nd punishment in ystdy and error remains.

**Comment by vingerha** [comment]
Better but not yet...
- pip uninstall pronotepy
- pip install https://github.com/bain3/pronotepy/archive/refs/heads/master.zip
- the same script test.py with serializer as above
```
python3 test.py
{'N': '133496952DB0623', 'G': 53, 'date': {'_T': 7, 'V': '19/10/2022'}, 'placeExecution': 4, 'duree': 60}
{
  "id": "11231A82509A784",
  "start": "2022-09-01 00:00:00",
  "name": "Trimestre 1",
  "end": "2022-11-23 00:00:00",
...
... **kicks back the 4 already retrievable**
...**the below line is new/different than before, followed by error**
{'N': '117393C3679A19A', 'G': 52, 'date': {'_T': 7, 'V': '03/03/2023'}}
Traceback (most recent call last):
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 206, in __call__
    json_value = json_value[p]
KeyError: 'duree'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 221, in __call__
    json_value = converter(json_value)
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 1833, in <lambda>
    lambda x: [Punishment.ScheduledPunishment(client, i) for i in x],
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 1833, in <listcomp>
    lambda x: [Punishment.ScheduledPunishment(client, i) for i in x],
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 1776, in __init__
    self.duration: datetime.timedelta = self._resolver(
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 216, in __call__
    raise ParsingError("Could not follow path", self.json_dict, path)
pronotepy.exceptions.ParsingError: Could not follow path

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/3692670A6ACD9016/docker/homeassistant1/python_scripts/pronote_old_attempts/test.py", line 39, in <module>
    serialized = period.to_dict(include_properties=True, exclude={"grades", "averages", "overall_average", "evaluations", "absences", "delays" })
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 282, in to_dict
    slot = getattr(self, slot_name)
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 523, in punishments
    return [Punishment(self._client, a) for a in absences if a["G"] == 41]
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 523, in <listcomp>
    return [Punishment(self._client, a) for a in absences if a["G"] == 41]
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 1832, in __init__
    self.schedule = self._resolver(
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 223, in __call__
    raise ParsingError(
pronotepy.exceptions.ParsingError: Error while converting value: Could not follow path
```

**Comment by bain3** [comment]
Hi, sorry, I've only tested it with detentions. It should now be `Optional`.

**Comment by vingerha** [comment]
Sorry for asking / not understanding. How would you expect me to test this now, the previous (above) script did not work, did you change anything today or how do I get the data out?

**Comment by vingerha** [comment]
OK, I repeated remove/install pronotepy and now it is working with above serilization script
As I am still (!) not the specialist, will this now work with current_period too?

**Comment by bain3** [comment]
The problem was that some fields were undefined in the response from pronote. Pronotepy assumed they would always be there, and so crashed when they were missing. It should work for all periods, including the current one.

**Comment by vingerha** [comment]
Thanks, as mentioned will further test later this weak and report any other issues if any, for now it looks good :)

**Comment by vingerha** [comment]
Confirming also current_period is working for me as well. 
Note that there is still a 'print' statement somewhere, giving out lines like this:
```
{'N': '117F763D7AC54CE', 'G': 52, 'date': {'_T': 7, 'V': '24/03/2023'}}
```
Any idea when this will end up in a release?

**Comment by vingerha** [comment]
And: THANKS

**Comment by bain3** [comment]
I'd like to release right after we close #213. Glad it works!
