### ISSUE TITLE
Unable to connect using Educonnect (MonENTOccitanie)

### ISSUE THREAD

**Issue by Freezman31** [bain3/pronotepy#233]
Hello !

Je suis élève dans un lycée en occitanie, et du coup j'ai la chance de pouvoir utiliser MonENTOccianite.
Lorsque j'essaye de me connecter en utilisant le cas `occitanie_toulouse_edu`, la lib me renvoie une erreur : 
```py
Traceback (most recent call last):
  File "C:\Users\xxxx\Dev\Random\pronotepy_test\main.py", line 6, in <module>
    client = pronotepy.Client('https://0312289v.index-education.net/pronote/eleve.html',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pronotepy\clients.py", line 352, in __init__
    super().__init__(pronote_url, username, password, ent, qr_code)
  File "C:\Python311\Lib\site-packages\pronotepy\clients.py", line 75, in __init__
    self.attributes, self.func_options = self.communication.initialise()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pronotepy\pronoteAPI.py", line 76, in initialise
    self.attributes = self._parse_html(get_response.content)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pronotepy\pronoteAPI.py", line 265, in _parse_html
    raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.
```

Voici mon code (honteusement copié de la doc 🥲)(les logins ont été cachés et je suis sûr que ce sont les bons, car dès que je les changent pour qqch d'erroné, j'obtiens l'erreur appropriée) : 
```py
import pronotepy
from pronotepy.ent import occitanie_toulouse_edu

# creating the client and passing the occitanie_montpellier function to automatically get cookies from ENT
client = pronotepy.Client('https://0312289v.index-education.net/pronote/eleve.html',
                          username='eeeeee',
                          password='eeeeee',
                          ent=occitanie_toulouse_edu)
# check if sucessfully logged in
if client.logged_in:
    print(len(client.grades())) # printing number of messages that the user has
else:
    print('no login')
```

Merci d'avance !

**Comment by bain3** [comment]
Hi,
can you please try using the latest version? You can install it using:
```
pip install -U git+https://github.com/bain3/pronotepy.git
```

**Comment by Freezman31** [comment]
I just tried, and it works !
Thank you !
Last question : do you know when this version will be pushed to the pip repositories ?

**Comment by bain3** [comment]
After #213 gets merged. I don't really have time to finish it and it seems that neither does @lucas-luchack.
