### ISSUE TITLE
Broken `ent_creuse`

### ISSUE THREAD

**Issue by bain3** [bain3/pronotepy#235]
```py
======================================================================
ERROR: test_functions (__main__.TestENT) [ent_creuse]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pronotepy/pronotepy/pronotepy/ent/test_ent.py", line 34, in test_functions
    func.result,
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/unittest/case.py", line 756, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/unittest/case.py", line 178, in handle
    callable_obj(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/runner/work/pronotepy/pronotepy/pronotepy/ent/generic_func.py", line 163, in _cas
    for input_ in form.findAll("input"):
AttributeError: 'NoneType' object has no attribute 'findAll'

----------------------------------------------------------------------
```

**Comment by Bapt5** [comment]
I will try to fix it soon
