### ISSUE TITLE
Another error after the new commit

### ISSUE THREAD

**Issue by karimk123** [bain3/pronotepy#24]
I updated to the latest version then just tried print(client.lessons("2021-01-30")) then i get this error:

Traceback (most recent call last): File "C:\Users\karim\Documents\Python Projects\Pronotepy\main.py", line 13, in <module> print(client.lessons("2021-01-30")) File "C:\Users\karim\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pronotepy\pronoteAPI.py", line 191, in lessons first_week = self.get_week(date_from) File "C:\Users\karim\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pronotepy\pronoteAPI.py", line 171, in get_week return 1 + int((date - self.start_day).days / 7) TypeError: unsupported operand type(s) for -: 'str' and 'datetime.date'

**Comment by bain3** [comment]
Hello, this is not a problem with pronotepy.

client.lessons expects `datetime.date`, not `str`. Correct example:

```py
import datetime # built-in datetime library
...
print(client.lessons(datetime.date(day=30, month=1, year=2021))
```
