### ISSUE TITLE
converter(json_value) - pronotepy.exceptions.ParsingError

### ISSUE THREAD

**Issue by sosordinet** [bain3/pronotepy#241]
Hello Bain3,
I have two childrens and since 10 days, i have an error on one of them on "Evaluations".
I suspect that teacher enter wrong date in this section and cause a "pronotepy.exceptions.ParsingError".

Can you tell me if there is a solution to this issue.

This is what i call:

`periods = [period.evaluations for period in client.periods]`

This is the error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pronotepy/dataClasses.py", line 222, in __call__
    json_value = converter(json_value)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pronotepy/dataClasses.py", line 126, in date_parse
    return datetime.datetime.strptime(formatted_date, "%d/%m/%Y").date()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: 17:00:00/2023

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/python_scripts/test.py", line 49, in <module>
    print(period.evaluations)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pronotepy/dataClasses.py", line 479, in evaluations
    return [Evaluation(e) for e in evaluations]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pronotepy/dataClasses.py", line 479, in <listcomp>
    return [Evaluation(e) for e in evaluations]
            ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pronotepy/dataClasses.py", line 1378, in __init__
    self.date: datetime.date = self._resolver(Util.date_parse, "date", "V")
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pronotepy/dataClasses.py", line 224, in __call__
    raise ParsingError(
pronotepy.exceptions.ParsingError: Error while converting value: unconverted data remains: 17:00:00/2023
```

There is no problem with the 2nd account with same command.
I have made severals test but nothing to resolve this issue. I need help.
Thanks in advance.

**Comment by bain3** [comment]
Hi, could you please run the following script and paste here the output?
```py
import pronotepy

client = ...

try:
    print(len([period.evaluations for period in client.periods]))
except pronotepy.ParsingError as e:
    print(e.__class__.__name__, ":", e)
    print(e.json_dict["date"]["V"])
```

It probably isn't the teacher's fault. I need to see the date format so I can update the parser.

**Comment by sosordinet** [comment]
Thank you.
This is the result:

```
ParsingError : Error while converting value: unconverted data remains: 17:00:00/2023
12/05/2023 17:00:00
```

**Comment by bain3** [comment]
Hi, I think I've solved the issue. Please try the latest version:
```
pip install -U git+https://github.com/bain3/pronotepy.git
```

**Comment by sosordinet** [comment]
Hi, all is good you solved the issue. There no error now.
Thank you for your reactivity. You are doing a very good job.
