### ISSUE TITLE
Problem during connect with 2 CAS

### ISSUE THREAD

**Issue by MaxenceLebrunDEV** [bain3/pronotepy#254]
Bonjour, j'ai un problème de connexion  avec les cas lyceeconnecte_edu & lyceeconnecte_aquitaine et les deux avec mes identifiants correspondant me ressorte ces problèmes:

```
root@debian-vertinon:/home/api# python3 test.py
Traceback (most recent call last):
  File "/home/api/test.py", line 6, in <module>
    client = pronotepy.Client('https://0400017b.index-education.net/pronote/eleve.html',
  File "/usr/local/lib/python3.9/dist-packages/pronotepy/clients.py", line 352, in __init__
    super().__init__(pronote_url, username, password, ent, qr_code)
  File "/usr/local/lib/python3.9/dist-packages/pronotepy/clients.py", line 75, in __init__
    self.attributes, self.func_options = self.communication.initialise()
  File "/usr/local/lib/python3.9/dist-packages/pronotepy/pronoteAPI.py", line 100, in initialise
    initial_response = self.post(
  File "/usr/local/lib/python3.9/dist-packages/pronotepy/pronoteAPI.py", line 181, in post
    raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: Unknown error from pronote: 21 | Impossible d'afficher la page
root@debian-vertinon:/home/api#
```

Si besoin je peut prêter un compte pour corriger le problème 
PS: j'ai la maj (pip install -U git+https://github.com/bain3/pronotepy@2023-compatibility)

**Comment by bain3** [comment]
Hi, I am deprecating ENTs (see #335).
