### ISSUE TITLE
OSE for College Blanqui in Bordeaux

### ISSUE THREAD

**Issue by Ogrinou** [bain3/pronotepy#259]
Hi, 
The URL is https://0331753b.index-education.net/pronote and it seems to use a local database.

Thank you.

**Comment by Ogrinou** [comment]
Thanks, but I did not manage to login with ent=None or ent="".

```
>>> client = pronotepy.Client('https://0331753b.index-education.net/pronote/parent.html',
... username='XXXXXXXXXXXX',
... password="XXXXXXXXXXXXXX")
>>> client.logged_in
True
>>> client.current_period
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/XXXXXXX/Src/pronotepy/pronotepy/clients.py", line 659, in current_period
    onglets = self.parametres_utilisateur["donneesSec"]["donnees"]["ressource"][
KeyError: 'listeOngletsPourPeriodes'
>>> client.get_teaching_staff()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/XXXXXXXX/Src/pronotepy/pronotepy/clients.py", line 537, in get_teaching_staff
    teachers = self.post("PageEquipePedagogique", 37)["donneesSec"]["donnees"][
KeyError: 'liste'
>>>
```

Most of that, I tried to scan the given QR Code and get this json : (X for obfuscation) 

```
{"jeton":"79.....XXXXX....XXXXX", "login": "B4.....XXXXXX", "url": "https://0331753b.index-education.net/pronote/mobile.parent.html"}
```

No uuid so I cannot use  pronotepy.Client.token_login

**Comment by bain3** [comment]
You make up / generate your own UUID. You do not receive it.

I'm not sure what's happening here though. It seems to work for others... Is your pronote fully open? Like can you find the information in the Vie Scolaire -> Equipe Pedagogique tab?

**Comment by Ogrinou** [comment]
Sorry, you can close this issue : everythink is ok now.
