### ISSUE TITLE
pronotepy not working with my PRONOTE (HTML parsing error)

### ISSUE THREAD

**Issue by Gaphilly-real** [bain3/pronotepy#278]
Hello,
I tried using `pronotepy` with my school's Pronote URL ([https://4170004n.index-education.net/pronote/](https://4170004n.index-education.net/pronote/)), but it doesn't work. The code I tried using was a program that fetched all evaluations and their grades and put them into a text file (I was just having fun with the module" Here is the exact code (note that it worked perfectly with the Pronote of my previous school ([https://pronote.lyceefrancais.be/pronote/](https://pronote.lyceefrancais.be/pronote/)))
```
import pronotepy
import datetime
import locale
locale.setlocale(locale.LC_TIME, 'fr_FR')

# Print the URL to ensure it's correct
pronote_url = 'https://4170004n.index-education.net/pronote/eleve.html?login=true'
print(f"Using Pronote URL: {pronote_url}")

# Get username and password from user input
username = input("What is your Pronote username?")
password = input("What is your Pronote password?")

try:
    client = pronotepy.Client(pronote_url, username=username, password=password)
    
    if client.logged_in:
        print("Successfully logged in.")
        periods = client.periods
        for i in periods:
            for j in i.evaluations:
                for k in j.acquisitions:
                    if k.name is not None:
                        file = open("Notes de l'année.txt", mode="a", encoding="utf-8")
                        file.write(f"Evaluation de {j.subject.name} du {j.date.strftime('%A %d %B %Y')} (avec {j.teacher}): {j.name}:\n{k.name} : {k.abbreviation} ({k.level}) (\n\n")
                        file.close()
    else:
        print("Failed to log in.")
except pronotepy.CryptoError:
    print("CryptoError: Unable to log in due to encryption issues.")
except Exception as e:
    print(f"An error occurred: {e}")
```
It gives me this error:
```
Traceback (most recent call last):
  File "C:\Users\Charlotte.Guillaume-PC\Desktop\Pronotepy\Evaluations.py", line 14, in <module>
    client = pronotepy.Client(pronote_url, username=username, password=password)
  File "C:\Users\Charlotte.Guillaume-PC\AppData\Roaming\Python\Python310\site-packages\pronotepy\clients.py", line 390, in __init__
    super().__init__(pronote_url, username, password, ent, mode, uuid)
  File "C:\Users\Charlotte.Guillaume-PC\AppData\Roaming\Python\Python310\site-packages\pronotepy\clients.py", line 81, in __init__
    self.attributes, self.func_options = self.communication.initialise()
  File "C:\Users\Charlotte.Guillaume-PC\AppData\Roaming\Python\Python310\site-packages\pronotepy\pronoteAPI.py", line 76, in initialise
    self.attributes = self._parse_html(get_response.content)
  File "C:\Users\Charlotte.Guillaume-PC\AppData\Roaming\Python\Python310\site-packages\pronotepy\pronoteAPI.py", line 263, in _parse_html
    raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.

```
I think this is due to the page HTML being this:
```
<html>
<body>
<!--StartFragment-->

  | <html><head><script type="text/javascript"><!--
-- | --
  | function leastFactor(n) {
  | if (isNaN(n) \|\| !isFinite(n)) return NaN;
  | if (typeof phantom !== 'undefined') return 'phantom';
  | if (typeof module !== 'undefined' && module.exports) return 'node';
  | if (n==0) return 0;
  | if (n%1 \|\| n*n<2) return 1;
  | if (n%2==0) return 2;
  | if (n%3==0) return 3;
  | if (n%5==0) return 5;
  | var m=Math.sqrt(n);
  | for (var i=7;i<=m;i+=30) {
  | if (n%i==0)      return i;
  | if (n%(i+4)==0)  return i+4;
  | if (n%(i+6)==0)  return i+6;
  | if (n%(i+10)==0) return i+10;
  | if (n%(i+12)==0) return i+12;
  | if (n%(i+16)==0) return i+16;
  | if (n%(i+22)==0) return i+22;
  | if (n%(i+24)==0) return i+24;
  | }
  | return n;
  | }
  | function go() {
  | var p=1711187192999; var s=3268030388; var n;
  | if ((s >> 1) & 1)p+= 215308051*2;/*
  | *13;
  | */else 	p-=882182310*/*
  | *13;
  | */2; if ((s >> 9) & 1)p+=/*
  | p+= */18396243*10;	else /*
  | *13;
  | */p-=/*
  | *13;
  | */131139576*	10;/*
  | p+= */if ((s >> 6) & 1)
  | p+=/*
  | p+= */210130316*
  | 9;	else 	p-=/* 120886108*
  | */291464968*	7;
  | if ((s >> 14) & 1)/*
  | else p-=
  | */p+=
  | 57263968*/* 120886108*
  | */17;else /* 120886108*
  | */p-=/* 120886108*
  | */141367057*/*
  | else p-=
  | */15;/*
  | else p-=
  | */if ((s >> 13) & 1)/*
  | p+= */p+=/* 120886108*
  | */16629510*/*
  | *13;
  | */14; else /*
  | p+= */p-=
  | 73500325*/*
  | else p-=
  | */14;  p+=4725800505;
  | n=leastFactor(p);
  | { document.cookie="KEY="+n+"*"+p/n+":"+s+":2466421144:1;path=/;";
  | document.location.reload(true); }
  | }
  | //--></script></head>
  | <body onload="go()">
  | Loading...
  | </body>
  | </html>
  |  

<!--EndFragment-->
</body>
</html>
```
which looks a lot like some obfuscated JS and the text "Loading...", instead of this:
```
<html>
<body>
<!--StartFragment-->

  | <!DOCTYPE html>
-- | --
  | <html lang="fr" xmlns="http://www.w3.org/1999/xhtml">
  | <head>
  | <base target="_blank" />
  | <link rel="schema.DC" href="http://purl.org/dc/elements/1.1/" />
  | <title>PRONOTE - LYCEE FRANCAIS JEAN MONNET</title>
  | <meta name="DC.title" content="PRONOTE - LYCEE FRANCAIS JEAN MONNET" />
  | <meta name="description" content="PRONOTE Page d'accueil - LYCEE FRANCAIS JEAN MONNET - BRUXELLES (099) - gestion des notes, absences, punitions, cahier de textes pour les établissements scolaires." />
  | <meta name="DC.description" content="PRONOTE Page d'accueil - LYCEE FRANCAIS JEAN MONNET - BRUXELLES (099) - gestion des notes, absences, punitions, cahier de textes pour les établissements scolaires." />
  | <meta name="DC.creator" content="LYCEE FRANCAIS JEAN MONNET" />
  | <meta name="DC.publisher" content="PRONOTE" />
  | <meta name="DC.coverage" content="BRUXELLES (099)" />
  | <meta name="geo.placename" content="BRUXELLES (099)" />
  | <meta name="robots" content="index" />
  | <link rel="apple-touch-icon" sizes="180x180" href="./images/apple-touch-icon.png" />
  | <link rel="icon" type="image/png" href="./images/favicon-32x32.png" sizes="32x32" />
  | <link rel="icon" type="image/png" href="./images/favicon-16x16.png" sizes="16x16" />
  | <link rel="manifest" href="./images/manifest.json" />
  | <link rel="mask-icon" sizes="any" href="./images/favicon.svg" color="#22874b">
  | <meta name="apple-mobile-web-app-title" content="PRONOTE" />
  | <meta name="application-name" content="PRONOTE" />
  | <meta name="theme-color" content="#22874b" />
  | <link rel="stylesheet" type="text/css" href="E_0_C_CE679C2475C309CAC745CA73009FE522D48EE948C77DEEF06576068063A5DC99_L_1036/espace/css/commun.css"/>
  | <script type="text/javascript" src="E_0_C_8884430512B27043B7B67AA0C33E5AB9439D0A2941F12126F41A1BD841682062_L_1036/commun_ext.js"></script>
  | <script type="text/javascript" src="E_0_C_9A72375DDDDAFB13B1CE7EBDC67653DE125D9C69FA46D847D7A99445EEDFDF16_L_1036/traductions.js"></script>
  | <script type="text/javascript" src="E_0_C_FA6E30A6BC8F72C8B3AF43A8617848A01131DA0BDE1823612B756439CD9DFC6E_L_1036/imagesconnexion.js"></script>
  | <script type="text/javascript" src="E_0_C_2025029CDF719FCA94A83DB4D45B7A79462D30D4C864717B3C63FB9A2F55E227_L_1036/commun.js"></script>
  | <script type="text/javascript">
  | require('deferLoadingScript.js').add ('jspdf', ['E_0_C_D9F97D890939B22C680BAC23E8365BF13EFB3D011C7647211FCB3B88F1FDE05A_L_1036/commun_jspdf.js']);
  | require('deferLoadingScript.js').add ('signature-pad', ['E_0_C_8BC556A9D8D419234B409E8A173FE39B4D1F6DC38938938F0AB534A1F51210BD_L_1036/commun_signature-pad.js']);
  | require('deferLoadingScript.js').add ('pep_poly', ['E_0_C_83CDBF56E33150423A376ACD38E95F37664C087ECB925AE3BDF42FD16E9B5B9C_L_1036/commun_pep_poly.js']);
  | </script>
  | <script type="text/javascript">
  | function messageErreur (e) {
  | $.get("erreur/" + e).fail(function (){}); alert ("Erreur sur le chargement de la page. Veuillez vider le cache de votre navigateur.")}
  | </script>
  | </head>
  | <body id="id_body" onload="try { Start ({h:'9321761',http:true,poll:true}) } catch (e) { messageErreur (e) } " class="EspaceIndex">
  | <noscript style="position: absolute; top: 100px" class="Texte12 Gras Espace">Java script non activé.
  | Veuillez le réactiver.</noscript>
  | <div id="div" data-role="page" class="NePasImprimer" style="height:100%"></div>
  | <a href="https://www.index-education.com/redirect.php?distrib=FR" target="_blank" style="display:none">PRONOTE 2023.0.2.4 gestion de vie scolaire, notes, compétences, absences/retards/dispenses, incidents/punitions/sanctions, stages... INDEX ÉDUCATION</a>
  | </body>
  | </html>
  |  

<!--EndFragment-->
</body>
</html>
```
which was the code of the page in my previous school, and is probably what `pronotepy` expects.
Now the question is:
# What can I do to fix this?

**Comment by bain3** [comment]
Hi! Looks like #194

**Comment by Gaphilly-real** [comment]
Yup, you're right! Hadn't seen it.

**Comment by Gaphilly-real** [comment]
Thx
