### ISSUE TITLE
Pronote 2024 : Cannot login (no "ressource" key)

### ISSUE THREAD

**Issue by GaPhi** [bain3/pronotepy#302]
Using 2.13.1 (updated within Home Assistant Pronote integration), when I try to login with QRCode and PIN, the login fails as there is no "ressource" key in "donnees" in "ParametresUtilisateur" response.

>   File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 259, in _login
    self, self.parametres_utilisateur["donneesSec"]["donnees"]["ressource"]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'ressource'


I have the same behavior in Chrome when using an URL without the "mobile." prefix... it is present in QRCode.

When I force this key value with the value I see with Chrome, login seems ok even if I do not see data grabbed afterward...


What can be the problem ?

**Comment by bain3** [comment]
Hi, do you have 2FA enabled on the account by any chance?

**Comment by bain3** [comment]
Hi, I can't reproduce the issue. I am able to log into a parent account with a QR code.

One thing seems off though. The line that the stack trace references is not correct. In `v2.13.1`, the code that is shown is on line 284.

**Comment by bain3** [comment]
I think it's related to 2FA. I am currently implementing support for accounts with strengthened security.

**Comment by GaPhi** [comment]
I tried the little piece of code of #302. I can reproduce the defect only with pronotepy without home-assistant integration.
I also tried to modify my password that was very complicated (with many special characters). With only uppercase, lowercase and digits (random password), the bug remains ; this is not due to it (that was probable as I use a qrCode...)

I also confirm that I do not have 2FA and this possibility is even not present on my account page.

**Comment by GaPhi** [comment]
In the HTTP connexion sequence, I see some difference (maybe because it is with login & password rather than qrCode) :
- In "Identification" request: donneesSec.donnees.genreEspace=2 rather than 7 with pronotepy
- In "Identification" response: donneesSec.donnees.alea is present (an UUID) but absent with pronotepy
- In "Authentification" request: espace=2 rather than 7 with pronotepy

I tried to force attribute["a"] = 2, this does not work better...

**Comment by bain3** [comment]
Hi, can you try to log in using the latest pronotepy's create_login?

```
pip install -U git+https://github.com/bain3/pronotepy
python3 -m pronotepy.create_login
```

**Comment by GaPhi** [comment]
Here is the result with a qrCode:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/pronotepy/create_login.py", line 58, in <module>
    exit(main())
         ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pronotepy/create_login.py", line 42, in main
    client = Client.qrcode_login(qr_code, pin, uuid)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 171, in qrcode_login
    return cls(urlunparse(fixed_url), login, jeton, mode="qr_code", uuid=uuid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 434, in __init__
    super().__init__(pronote_url, username, password, ent, mode, uuid)
  File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 119, in __init__
    self.logged_in = self._login()
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 285, in _login
    self, self.parametres_utilisateur["donneesSec"]["donnees"]["ressource"]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'ressource'
```

**Comment by bain3** [comment]
Hi, that is not the correct version it seems. Please install pronotepy from git with the command I sent above and try again. I am getting the same error on an account that has higher security enabled (like keeping a list of recognized devices).

**Comment by tibohlami** [comment]
@bain3 it works for me ! (I used to have the same `KeyError: 'ressource'` before)
The only nit : I had to add the `device_name` entry in the creds structure returned by create_login before calling `token_login()`
(and also add it to the new creds returned by `Client.export_credentials`)

**Comment by bain3** [comment]
Interesting. That means that pronotepy needs to re-register itself as a device every time you log in. I mean if it works for you, then that's great. But from my testing, you should be able to register the device once, and then continue to use it with the client_identifier.

**Comment by tibohlami** [comment]
Let me try this again; just to make sure I didn't mess up my test

**Comment by tibohlami** [comment]
Ok I tried again from scratch and it worked without adding the device_name; probably mistake on my side, sorry about that.

But yeah it works; thanks a lot @bain3 !

**Comment by GaPhi** [comment]
> Hi, that is not the correct version it seems. Please install pronotepy from git with the command I sent above and try again. I am getting the same error on an account that has higher security enabled (like keeping a list of recognized devices).

I did 
```bash
pip install -U git+https://github.com/bain3/pronotepy
python3 -m pronotepy.create_login
```
Then I typed the url, login, passwd, no ENT, and got this global console:
<details>
<summary>Console with login/passwd</summary>

```
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting git+https://github.com/bain3/pronotepy
  Cloning https://github.com/bain3/pronotepy to /tmp/pip-req-build-8gczy287
  Running command git clone --filter=blob:none --quiet https://github.com/bain3/pronotepy /tmp/pip-req-build-8gczy287
  Resolved https://github.com/bain3/pronotepy to commit 211af7fc313866b0afb493977719d89decd41178
  Preparing metadata (setup.py) ... done
Requirement already satisfied: beautifulsoup4>=4.8.2 in /usr/local/lib/python3.12/site-packages (from pronotepy==2.13.1) (4.12.3)
Requirement already satisfied: pycryptodome>=3.9.4 in /usr/local/lib/python3.12/site-packages (from pronotepy==2.13.1) (3.20.0)
Requirement already satisfied: requests>=2.22.0 in /usr/local/lib/python3.12/site-packages (from pronotepy==2.13.1) (2.32.3)
Requirement already satisfied: autoslot>=2022.12.1 in /usr/local/lib/python3.12/site-packages (from pronotepy==2.13.1) (2022.12.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/site-packages (from beautifulsoup4>=4.8.2->pronotepy==2.13.1) (2.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.12/site-packages (from requests>=2.22.0->pronotepy==2.13.1) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/site-packages (from requests>=2.22.0->pronotepy==2.13.1) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/site-packages (from requests>=2.22.0->pronotepy==2.13.1) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/site-packages (from requests>=2.22.0->pronotepy==2.13.1) (2024.8.30)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
JSON QR code contents (leave blank for user/pass login):

Please input the full url ending with eleve/parent.html
URL of your pronote instance: https://0951710t.index-education.net/pronote/parent.html
Your ENT (name of an ENT function, or leave empty):
Your login username: PGRESSELUGUE
Your login password:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/pronotepy/create_login.py", line 58, in <module>
    exit(main())
         ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pronotepy/create_login.py", line 31, in main
    client = Client(url, username, password, ent)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 434, in __init__
    super().__init__(pronote_url, username, password, ent, mode, uuid)
  File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 119, in __init__
    self.logged_in = self._login()
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 285, in _login
    self, self.parametres_utilisateur["donneesSec"]["donnees"]["ressource"]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'ressource'
```
</details>

I have quite the same with qrCode:
<details>
<summary>Console with qrCode</summary>

```
JSON QR code contents (leave blank for user/pass login): {"avecPageConnexion":false,"jeton":"85ED735B02DAEEAEE32FF136CE063529E6A21E9008A508203750AD58D63048FE592AFFC2E70DB2A2D809DA1FB3AE2B3ECBD54AA32D80B882A9899BCA10FC4241703CEC3976B243D828DC67AEFCEED38A33A7413800FFE9B16990AD038881A96EB672991A6F751E27614A06166733419E","login":"9853E08FC87325079B15476175D96EEC","url":"https://0951710t.index-education.net/pronote/mobile.parent.html"}
QR code PIN: 0000
Application UUID, preferably something random (leave blank for random):
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/pronotepy/create_login.py", line 58, in <module>
    exit(main())
         ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pronotepy/create_login.py", line 42, in main
    client = Client.qrcode_login(qr_code, pin, uuid)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 171, in qrcode_login
    return cls(urlunparse(fixed_url), login, jeton, mode="qr_code", uuid=uuid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 434, in __init__
    super().__init__(pronote_url, username, password, ent, mode, uuid)
  File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 119, in __init__
    self.logged_in = self._login()
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 285, in _login
    self, self.parametres_utilisateur["donneesSec"]["donnees"]["ressource"]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'ressource'
```
</details>

**Comment by GaPhi** [comment]
> Interesting. That means that pronotepy needs to re-register itself as a device every time you log in. I mean if it works for you, then that's great. But from my testing, you should be able to register the device once, and then continue to use it with the client_identifier.

How can I try to register my pronotepy instance as a new device using pronotepy ?
Just to try it as my account has a "Moyen" level of security set? (see screen capture)
![Capture](https://github.com/user-attachments/assets/8876f606-2da3-4a0c-b868-c114dcd6f5f6)

This might be consistent to the error message received "Vos droits sont insuffisants pour effectuer cette opération"...

**Comment by GaPhi** [comment]
I have create 2 HAR log files with and without device registration, starting from a "private navigation" browser.
When I do not register the device, the connection is aborted.
When I register a new device (named "Test" in the log), the connection succeed.

I can provide those 2 log files, if you want to check anything in them, I really think we are on the right way.

Thanks !

**Comment by GaPhi** [comment]
Thanks a lot, it is OK with pronotepy now! Well done!

Just have to let home assistant integration implement this device registration too now... But this is for another GitHub project.
Is this working version available as an official release version?

Thank you very much for your support and time!

**Comment by bain3** [comment]
Great!

**Comment by GaPhi** [comment]
I create the code for the Home Assistant integration : [#82](https://github.com/delphiki/hass-pronote/pull/82)

I tested it and it is ok with login/password process.

Can we also use de qrCode process with device_name or account_pin parameters ? (I did not code it nor tried it yet)
If it is also possible, I can finalize the update with this process too.

**Comment by bain3** [comment]
Yes, you can just pass it into [`qrcode_login`](https://pronotepy.readthedocs.io/en/v2.14.0/api/clients.html#pronotepy.ClientBase.qrcode_login).

**Comment by GaPhi** [comment]
In [the documentation](https://pronotepy.readthedocs.io/en/v2.14.0/api/clients.html#), the new class members are missing but not in the implemented code:
- account_pin
- client_identifier
- device_name

Ok, I try to implement this too then.

**Comment by GaPhi** [comment]
This is not working with a fresh qrCode & device_name.
<details><summary>The code</summary>

```python
from pyzbar.pyzbar import decode
from PIL import Image
import pronotepy
import json
from uuid import uuid4
import datetime

import logging
from pronotepy.pronoteAPI import (
    log,
)
log.setLevel(logging.DEBUG)
console_handler = logging.StreamHandler()
console_handler.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(levelname)s - %(message)s')
console_handler.setFormatter(formatter)
log.addHandler(console_handler)


img = Image.open('Capture.PNG')

decoded_objects = decode(img)

print(decoded_objects)
try:
    qrcode_data=json.loads(decoded_objects[0].data.decode("utf-8"))
except Exception as e:
    print(f"Can not decode QR code: {str(e)}")
    exit()

pin="0000"
uuid=uuid4()
print(uuid)

try:
    client=pronotepy.Client.qrcode_login(
            qrcode_data,
            pin,
            str(uuid),
            device_name="Toto")
except Exception as e:
    print(f"Can not login with QR code: {str(e)}")
    exit()

credentials = {
    "url": client.pronote_url,
    "username": client.username,
    "password": client.password,
    "uuid": client.uuid,
    "account_pin": client.account_pin,
    "device_name": client.device_name,
    "client_identifier": client.client_identifier,
    
}
print(credentials)
```

</details>

<details><summary>Resulting stdout</summary>

```
[Decoded(data=b'{"avecPageConnexion":false,"jeton":"EFFED9C754353B5579E3FDD78A8775DC9B6BFF124BB14D2F8ADF12C147B069952856760597114F25F5C20089D859E8AA88659FAC6DE0813A3DB8A079FF81FB41DE81502E462997CD18C37968D5DF242B96993565491C930011AA848021CCA86275DF7CFF9BCDD02C56C8BB30C7463FBF","login":"9853E08FC87325078B15476175D96EEC","url":"https://0951710t.index-education.net/pronote/mobile.parent.html"}', type='QRCODE', rect=Rect(left=23, top=10, width=276, height=276), polygon=[Point(x=23, y=10), Point(x=23, y=286), Point(x=298, y=285), Point(x=299, y=10)])]
a1bae25b-87b8-471a-b0e0-c91a672c0c17
INFO - INIT
DEBUG - Requesing html: https://0951710t.index-education.net/pronote/mobile.parent.html?fd=1&bydlg=A6ABB224-12DD-4E31-AD3E-8A39A1C2C335&login=true
DEBUG - [_Communication.post] sending post request: {'session': 9043438, 'numeroOrdre': '3fa959b13967e0ef176069e01e23c8d7', 'nom': 'FonctionParametres', 'donneesSec': {'donnees': {'Uuid': 'o052NOxIyEDphOgk4bXKUg==', 'identifiantNav': None}}}
DEBUG - [_Communication.post] decryption change
DEBUG - [_Communication.post] sending post request: {'session': 9043438, 'numeroOrdre': '6e2dd9f3cbc55363fe9f84e3404c92f0', 'nom': 'Identification', 'donneesSec': {'donnees': {'genreConnexion': 0, 'genreEspace': 7, 'identifiant': 'pgresselugue', 'pourENT': False, 'enConnexionAuto': False, 'demandeConnexionAuto': False, 'demandeConnexionAppliMobile': True, 'demandeConnexionAppliMobileJeton': True, 'enConnexionAppliMobile': False, 'uuidAppliMobile': 'a1bae25b-87b8-471a-b0e0-c91a672c0c17', 'loginTokenSAV': ''}}}
DEBUG - indentification
DEBUG - {'nom': 'Identification', 'session': 9043438, 'numeroOrdre': '0B41B9AD0CEF079209FD6A8CBE125403', 'donneesSec': {'donnees': {'modeCompMdp': 0, 'modeCompLog': 1, 'challenge': 'AC6FA2C32619BBE0F8264C5CDE89E572B2B838346CD728F47DBE88992F81EDBA590681B1EA8F09D103B8BF02D7300D42'}, 'nom': 'Identification'}}
DEBUG - [_Communication.post] sending post request: {'session': 9043438, 'numeroOrdre': '9ea2064476d6344d79d5ca95a06147f5', 'nom': 'Authentification', 'donneesSec': {'donnees': {'connexion': 0, 'challenge': '970b9ff1b444999701cab2981b1e8b1ce34a5238f39f3fbaa43a7db446b829ea', 'espace': 7}}}
DEBUG - doing 2fa doPin=False, doRegister=True, pin=False (redacted), identifier=Toto
DEBUG - registering device
DEBUG - [_Communication.post] sending post request: {'session': 9043438, 'numeroOrdre': 'b880f57f24aedf8d2289f5d570d5f657', 'nom': 'SecurisationCompteDoubleAuth', 'donneesSec': {'donnees': {'action': 3, 'avecIdentification': True, 'strIdentification': 'Toto'}}}
INFO - successfully logged in as pgresselugue
DEBUG - [_Communication.post] sending post request: {'session': 9043438, 'numeroOrdre': 'b9c1f44e0cb8319b77a87d2939bfdb31', 'nom': 'ParametresUtilisateur', 'donneesSec': {}}
INFO - got onglets data.
DEBUG - [_Communication.post] sending post request: {'session': 9043438, 'numeroOrdre': 'c3de062200835bbe2c71917b9c1cc0a5', 'nom': 'PageInfosPerso', 'donneesSec': {'_Signature_': {'onglet': 49}}}
INFO - Have you tried turning it off and on again? ERROR: 3 | Accès refusé
DEBUG - Requesing html: https://0951710t.index-education.net/pronote/mobile.parent.html?fd=1&bydlg=A6ABB224-12DD-4E31-AD3E-8A39A1C2C335&login=true
DEBUG:pronotepy.pronoteAPI:Requesing html: https://0951710t.index-education.net/pronote/mobile.parent.html?fd=1&bydlg=A6ABB224-12DD-4E31-AD3E-8A39A1C2C335&login=true
DEBUG - [_Communication.post] sending post request: {'session': 8340147, 'numeroOrdre': '3fa959b13967e0ef176069e01e23c8d7', 'nom': 'FonctionParametres', 'donneesSec': {'donnees': {'Uuid': '5t6yp5myDZrrhLKg0GbR5g==', 'identifiantNav': '93DD9B14D6794F65699EEE658C7EA0247E82E85C0BF4A1574A24982426791451D2668C496FB40CD8DE5C2FBA75B167180885E94900000000'}}}
DEBUG:pronotepy.pronoteAPI:[_Communication.post] sending post request: {'session': 8340147, 'numeroOrdre': '3fa959b13967e0ef176069e01e23c8d7', 'nom': 'FonctionParametres', 'donneesSec': {'donnees': {'Uuid': '5t6yp5myDZrrhLKg0GbR5g==', 'identifiantNav': '93DD9B14D6794F65699EEE658C7EA0247E82E85C0BF4A1574A24982426791451D2668C496FB40CD8DE5C2FBA75B167180885E94900000000'}}}
DEBUG - [_Communication.post] decryption change
DEBUG:pronotepy.pronoteAPI:[_Communication.post] decryption change
DEBUG - [_Communication.post] sending post request: {'session': 8340147, 'numeroOrdre': '4083e11f4bdc50220a7661dd4bd1c4e9', 'nom': 'Identification', 'donneesSec': {'donnees': {'genreConnexion': 0, 'genreEspace': 7, 'identifiant': 'pgresselugue', 'pourENT': False, 'enConnexionAuto': False, 'demandeConnexionAuto': False, 'demandeConnexionAppliMobile': True, 'demandeConnexionAppliMobileJeton': True, 'enConnexionAppliMobile': False, 'uuidAppliMobile': 'a1bae25b-87b8-471a-b0e0-c91a672c0c17', 'loginTokenSAV': ''}}}
DEBUG:pronotepy.pronoteAPI:[_Communication.post] sending post request: {'session': 8340147, 'numeroOrdre': '4083e11f4bdc50220a7661dd4bd1c4e9', 'nom': 'Identification', 'donneesSec': {'donnees': {'genreConnexion': 0, 'genreEspace': 7, 'identifiant': 'pgresselugue', 'pourENT': False, 'enConnexionAuto': False, 'demandeConnexionAuto': False, 'demandeConnexionAppliMobile': True, 'demandeConnexionAppliMobileJeton': True, 'enConnexionAppliMobile': False, 'uuidAppliMobile': 'a1bae25b-87b8-471a-b0e0-c91a672c0c17', 'loginTokenSAV': ''}}}
DEBUG - indentification
DEBUG:pronotepy.pronoteAPI:indentification
DEBUG - {'nom': 'Identification', 'session': 8340147, 'numeroOrdre': 'F5A44F568C4449D69BBE7EAE543C1FDD', 'donneesSec': {'donnees': {'modeCompMdp': 0, 'modeCompLog': 1, 'challenge': 'D5DB90895E9F33776C211865D2E40BB8872DADAB43EAB203166838AE355C1CD0255789115C08176315C1CDE477FEE8BE'}, 'nom': 'Identification'}}
DEBUG:pronotepy.pronoteAPI:{'nom': 'Identification', 'session': 8340147, 'numeroOrdre': 'F5A44F568C4449D69BBE7EAE543C1FDD', 'donneesSec': {'donnees': {'modeCompMdp': 0, 'modeCompLog': 1, 'challenge': 'D5DB90895E9F33776C211865D2E40BB8872DADAB43EAB203166838AE355C1CD0255789115C08176315C1CDE477FEE8BE'}, 'nom': 'Identification'}}
Can not login with QR code: ('Decryption failed while trying to un pad. (probably bad decryption key/iv)', 'exception happened during login -> probably the qr code has expired (qr code is valid during 10 minutes)')
```

</details>

**Comment by GaPhi** [comment]
Thanks once again... I'm a bit stupid sometimes. ;-)

Implementation completed and pushed to home assistant projet into the same pull request [#82](https://github.com/delphiki/hass-pronote/pull/82) .
