### ISSUE TITLE
Error after some period using QR&token login

### ISSUE THREAD

**Issue by bdbogjoe** [bain3/pronotepy#309]
i update to 2.14.1, issue with QR login is fixed, but i'm still having the issue of expiration after few hours (last time 6h)

```
2024-09-19 17:20:19,026 - pronote-rest - ERROR - Unknown error from pronote: 8 | La page a expiré ! (1)
2024-09-19 17:20:19,026 - pronote-rest - ERROR - Unknown error from pronote: 8 | La page a expiré ! (1)
Traceback (most recent call last):
  File "/home/app/.local/lib/python3.10/site-packages/pronotepy/clients.py", line 1061, in post
    return self.communication.post(function_name, post_data)
  File "/home/app/.local/lib/python3.10/site-packages/pronotepy/pronoteAPI.py", line 179, in post
    raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: Unknown error from pronote: 8 | La page a expiré ! (1)
```

To try to fix this, i added cron every minute to refresh session using  `client.session_check()` but did not solve. Still having this page expired :(

**Comment by SleepInfinity** [comment]
I'm having the same issue even when i'm sending requests to pronote every 5 minutes to check for new homework or grades.
i don't know what is the problem.

**Comment by KheroubiAymen** [comment]
same

**Comment by fafoulon** [comment]
I also have the same problem
