### ISSUE TITLE
Issue with PYthon 3.11 ?

### ISSUE THREAD

**Issue by Aldarande** [bain3/pronotepy#319]
I have this result in Python 3.11 for :
pronotepy.Client.qrcode_login(
        qrcode_data,
        str(1234),
        uuid="ProJote",
    )

`Traceback (most recent call last):
  File "/var/www/html/plugins/ProJote/resources/python_venv/lib/python3.11/site-packages/pronotepy/clients.py", line 547, in post
    return self.communication.post(function_name, post_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/plugins/ProJote/resources/python_venv/lib/python3.11/site-packages/pronotepy/pronoteAPI.py", line 179, in post
    raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: Unknown error from pronote: 3 | Accès refusé

During handling of the above exception, another exception occurred:'

but in 3.9 version i don't have any issue.
What can i do for it's work on 3.11 ?

**Comment by Aldarande** [comment]
I found the issue, in fact they have any report with Python's version

**Comment by Aldarande** [comment]
In fact the issue is doesn't link to Python's version, but i don't understand qrcode_login need to be link with Client or ParentClient usage.
