### ISSUE TITLE
ENT Normandie

### ISSUE THREAD

**Issue by MoreOwO** [bain3/pronotepy#40]
I'm trying to connect to pronote with pronote py like this : `pronote = pronotepy.Client('http://vs.lvh.lyc14.ac-caen.fr:81/pronote/eleve.html', username='',password='')`, but i've this error :
```
Traceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "F:\Python\PronoteBot\main.py", line 17, in refr_tb
    pronote = pronotepy.Client('http://vs.lvh.lyc14.ac-caen.fr:81/pronote/eleve.html', username='',
  File "C:\Users\romeo\AppData\Local\Programs\Python\Python39\lib\site-packages\pronotepy\pronoteAPI.py", line 71, in __init__
    self.attributes, self.func_options = self.communication.initialise()
  File "C:\Users\romeo\AppData\Local\Programs\Python\Python39\lib\site-packages\pronotepy\pronoteAPI.py", line 367, in initialise
    self.attributes = self._parse_html(get_response.content)
  File "C:\Users\romeo\AppData\Local\Programs\Python\Python39\lib\site-packages\pronotepy\pronoteAPI.py", line 497, in _parse_html
    raise PronoteAPIError(
pronotepy.pronoteAPI.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.
```
and idk why. 
Is this the right url ?

**Comment by bain3** [comment]
Hello,
your Pronote uses an ENT. I don't think we support your ENT yet. You can try to add `?login=true` to the url, but its not a certain solution.

**Comment by MoreOwO** [comment]
Okay thanks, i'll try that, hope my ent will be implemented soon.

**Comment by tarneaux** [comment]
Hi,
You can try to change URLs in ent.py.
For example modify the ac_reims function so that the url is your ENT's login url.
Try this with every ENT function and you should find one that is made like yours.
This is what I did for my ent and it worked first try.
