### ISSUE TITLE
Login using EduConnect

### ISSUE THREAD

**Issue by ascpial** [bain3/pronotepy#45]
Pronote in Grand Est (MBN, MonBureauNumerique) use EduConnect to login.
How can I use pronotepy to login into pronote ?

**Comment by ascpial** [comment]
I have add a function for my ent, but it return this error : 
`Traceback (most recent call last):
  File "C:\Users\Elève\fabert\test_pronotepy.py", line 7, in <module>
    client = pronotepy.Client("http://pronote.lycee-fabert.com/pronote/eleve.html",
  File "C:\Users\Elève\AppData\Local\Programs\Python\Python39\lib\site-packages\pronotepy\clients.py", line 270, in __init__
    super().__init__(pronote_url, username, password, ent)
  File "C:\Users\Elève\AppData\Local\Programs\Python\Python39\lib\site-packages\pronotepy\clients.py", line 58, in __init__
    self.attributes, self.func_options = self.communication.initialise()
  File "C:\Users\Elève\AppData\Local\Programs\Python\Python39\lib\site-packages\pronotepy\pronoteAPI.py", line 58, in initialise
    self.attributes = self._parse_html(get_response.content)
  File "C:\Users\Elève\AppData\Local\Programs\Python\Python39\lib\site-packages\pronotepy\pronoteAPI.py", line 188, in _parse_html
    raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.`

**Comment by Xiloe** [comment]
Your pronote URL is wrong or your function doesn't connect properly to the ENT and doesn't return the good cookies to pronote.

"Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page."
That means that you are not connected to pronote, try checking the request.text, if you see that it's your ENT website, then your implementation is wrong.

Look at my Montpellier ENT implementation for more infos, it uses EduConnect. Just copy paste it and change what you need to change. Hope it helps you.

**Comment by ascpial** [comment]
Actually I have resolve the error, caused by a change in the header.
If you want, I can make a PR for the implementation of MBN (monbureanumerique)

**Comment by Xiloe** [comment]
Yeah, do I PR and I'll review it :) Can I close the issue ?

**Comment by ascpial** [comment]
I dot it _
