### ISSUE TITLE
I have an error :

### ISSUE THREAD

**Issue by YoYomec** [bain3/pronotepy#85]
hello, i have instaled pronotepy with `pip install pronotepy`
and I write this code :
```
import pronotepy

client = pronotepy.Client('https://0311582b.index-education.net/pronote/eleve.html', username='secret', password='secret')

if client.logged_in:
    print("test")
```
I execute the code and I see this :
```
Traceback (most recent call last):
  File "c:/Users/myName/Desktop/Python/pronote/notes.py", line 3, in <module>
    client = pronotepy.Client('https://xxxxxxxx.index-education.net/pronote/eleve.html', username='secret', password='secret')
  File "C:\ProgramData\Anaconda3\lib\site-packages\pronotepy\clients.py", line 283, in __init__
    super().__init__(pronote_url, username, password, ent)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pronotepy\clients.py", line 58, in __init__
    self.attributes, self.func_options = self.communication.initialise()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pronotepy\pronoteAPI.py", line 60, in initialise
    self.attributes = self._parse_html(get_response.content)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pronotepy\pronoteAPI.py", line 203, in _parse_html
    raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.
```

**Comment by Vexcited** [comment]
This is because your Pronote URL redirects to your ENT.

There's two solutions:
- If you know your ENT IDs and the ENT is listed in Pronotepy, then refer to [the documentation about it](https://github.com/bain3/pronotepy#ent).
- Append `?login=true` at the end of the Pronote string URL so it will end up with something like `https://id.index-education.net/pronote/eleve.html?login=true`

Hope it helped !
